apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: frontend
  namespace: default
spec:
  protocol: http
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
  namespace: default
spec:
  config:
    protocol: http
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: ingress-to-frontend
  namespace: default
spec:
  destination:
    name: frontend
  sources:
    - name: ingress-gateway
      action: allow
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:
  name: ingress-gateway
  namespace: default
spec:
  listeners:
    - port: 80
      protocol: http
      services:
        - name: frontend
          hosts: ["*"]