apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
    name: ingress-to-frontend
    namespace: default
spec:
    destination:
        name: frontend
    sources:
        - name: ingress-gateway
          action: allow