apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  destination:
    name: {{ .Values.destination.name }}
  sources:
    - name: {{ .Values.sources.name }}
      action: {{ .Values.sources.action }}
