---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: app
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  labels:
    {{- include "mychart.selectorLabels" . | indent 4 }}