---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: app
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "mychart.selectorLabels" . | indent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}