apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana-intention
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: 'monitoring'
    server: https://kubernetes.default.svc
  source:
    path: helm/service-intentions
    repoURL: https://github.com/monukoni/kubernetes
    targetRevision: add-argocd
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
