name: ci-cd

on: 
    push:
        branches: [main]
    pull_request:
    
jobs:
    lint:
        uses: ./.github/workflows/lint.yml
        permissions:
            contents: write
            pull-requests: write

    changes:
      runs-on: ubuntu-latest
      outputs:
        backend: ${{ steps.changes.outputs.backend }}
        frontend: ${{ steps.changes.outputs.frontend }}
      steps:
        - uses: actions/checkout@v4
        - uses: dorny/paths-filter@v3
          id: changes
          with:
            filters: |
              backend:
                - 'src/backend/**'
                - '.github/workflows/push-docker.yml' 
              frontend:
                - 'src/frontend/**'
                - '.github/workflows/push-docker.yml' 

    backend-push:
        if: ${{ needs.changes.outputs.backend == 'true' }}
        uses: ./.github/workflows/push-docker.yml
        needs: ["lint", "changes"]
        secrets:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        with:
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          AWS_REGION: 'eu-central-1'
          CONTAINER_NAME: backend

    frontend-push:
      if: ${{ needs.changes.outputs.frontend == 'true' }}
      uses: ./.github/workflows/push-docker.yml
      needs: ["lint", "changes"]
      secrets:
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      with:
        AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
        AWS_REGION: 'eu-central-1'
        CONTAINER_NAME: frontend

    approve: 
        runs-on: ubuntu-latest
        needs: ["lint", "backend-push", "frontend-push"]
        if: >-
          always() && 
          needs.lint.result == 'success' &&
          (needs.backend-push.result == 'success' || needs.backend-push.result == 'skipped') &&
          (needs.frontend-push.result == 'success' || needs.frontend-push.result == 'skipped')
        timeout-minutes: 1
        permissions:
            issues: write
        steps:
            - uses: trstringer/manual-approval@v1
              with:
                approvers: monukoni
                secret: ${{ github.TOKEN }}
                minimum-approvals: 1
                exclude-workflow-initiator-as-approver: false
                fail-on-denial: true
            
    deploy:
        needs: [approve]
        uses: ./.github/workflows/cd.yml
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}