name: ci-cd

on: 
    push:
        branches: [main]
    pull_request:
    
jobs:
    # lint:
    #     uses: ./.github/workflows/lint.yml
    #     permissions:
    #         contents: read
    #         pull-requests: write

    # approve: 
    #     runs-on: ubuntu-latest
    #     needs: ["lint"]
    #     timeout-minutes: 3
    #     permissions:
    #         issues: write
    #     steps:
    #         - uses: trstringer/manual-approval@v1
    #           with:
    #             approvers: monukoni
    #             secret: ${{ github.TOKEN }}
    #             minimum-approvals: 1
    #             exclude-workflow-initiator-as-approver: false
    #             fail-on-denial: true
            
    deploy:
        # needs: [approve]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: .github/workflows/cd.yml
